name: Tests for obuilderfs
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON  
    
jobs:
  test:
    strategy:
      matrix:
        operating-system: [macos-11, macos-12]
    runs-on: ${{ matrix.operating-system }}
    steps: 
    - uses: actions/checkout@v3
    - name: Get FUSE for OSX
      run: brew install --cask macfuse
    - name: Builds
      run: make 
    - name: Info
      run: ./install/obuilderfs --help
